version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - package-ecosystem: "pip"
    directory: "backend"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
