repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest before commit
        entry: pytest tests/
        language: system
        pass_filenames: false
        always_run: true
