name: Python Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    name: Detect Python Changes
    runs-on: ubuntu-latest

    outputs:
      python: ${{ steps.filter.outputs.python }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Python files changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**/*.py'
              - 'backend/requirements.txt'
              - 'backend/requirements-dev.txt'
  test:
    name: Run Python Tests
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.python == 'true'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt', 'backend/requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r backend/requirements-dev.txt

    - name: Run tests
      run: |
        coverage run -m pytest
        coverage report --fail-under=90
        coverage html

    - name: Save coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/